name: presensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0-21.0.dev <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^2.10.0
  firebase_auth: 4.4.2
  cloud_firestore: 4.5.3
  image_picker: 0.8.7+4
  firebase_storage: 11.1.2
  path_provider: 2.0.15
  convex_bottom_bar: 3.2.0
  intl: 0.18.1
  geolocator: 9.0.2
  geocoding: 2.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

